import { SignedIn, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useState } from "react";
import Divider from "~/components/utils/Divider";
import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();

  const CreatePostWizard = () => {
    const { user } = useUser();

    if (!user) return null;

    const [searhVal, setsearhVal] = useState("");

    return (
      <div className="flex w-full max-w-[500px] items-center justify-center gap-2.5 rounded-md border border-slate-200 border-opacity-30 bg-slate-200 bg-opacity-10 p-2.5">
        <input
          type="text"
          placeholder="Type some emojis!"
          className="w-full bg-transparent outline-none"
          maxLength={250}
          onChange={(event) => setsearhVal(event.target.value)}
        />
        <span>{searhVal.length}/250</span>
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full flex-col items-center justify-start">
        <section
          id="#"
          className="flex min-h-screen w-full flex-col items-center justify-start"
        >
          <Divider />
          <div className="flex w-full flex-1 flex-col items-center justify-stretch gap-5 p-5  md:gap-10 md:p-10 lg:p-20 lg:pt-10">
            <SignedIn>
              <CreatePostWizard />
            </SignedIn>
            <div className="flex w-full max-w-[500px] flex-col items-center justify-center gap-1 rounded-md border border-slate-200 border-opacity-30 bg-slate-200 bg-opacity-10 ">
              {!isLoading ? (
                data ? (
                  data.map((post, index) => (
                    <div
                      className="w-full items-center justify-start  p-2"
                      key={index}
                    >
                      {post.content}
                    </div>
                  ))
                ) : (
                  <div>Something went wrong</div>
                )
              ) : (
                <div>Loading..</div>
              )}
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
